# Generated by Django 6.0 on 2026-01-06 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand/Model name', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('imei_number', models.CharField(help_text='IMEI Number', max_length=15, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price we bought', max_digits=10)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price we will/did sell', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
                ('stock_in_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date added to stock')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=15, null=True)),
                ('sold_date', models.DateTimeField(blank=True, help_text='Date sold', null=True)),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
                'ordering': ['-stock_in_date'],
            },
        ),
    ]
