# Generated by Django 6.0 on 2026-01-06 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('state_code', models.CharField(help_text='State code e.g., 36 for Telangana', max_length=2)),
                ('gstin', models.CharField(help_text='GSTIN/UIN', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(default='Venkateshwara Mobiles Sales & Services', max_length=200)),
                ('company_address', models.CharField(default='Tilak Garden Complex, Nizamabad', max_length=300)),
                ('company_gstin', models.CharField(default='36CHEPM3931K1Z5', max_length=15)),
                ('company_state', models.CharField(default='Telangana', max_length=50)),
                ('company_state_code', models.CharField(default='36', max_length=2)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9, help_text='CGST percentage', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9, help_text='SGST percentage', max_digits=5)),
                ('delivery_note', models.CharField(blank=True, max_length=200)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(default='85171300', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.invoice')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.mobile')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['invoice', 'id'],
            },
        ),
    ]
