# Generated by Django 6.0 on 2026-01-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_gstin',
            field=models.CharField(default='', help_text='GSTIN/UIN', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_state_code',
            field=models.CharField(default='', help_text='State code e.g., 36 for Telangana', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.customer'),
        ),
    ]
