# Generated by Django 6.0 on 2026-01-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_invoice_buyer_address_invoice_buyer_gstin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
